# Generated by Django 2.1.5 on 2022-06-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0002_herec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_rezie', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='rezie',
        ),
        migrations.AddField(
            model_name='rezie',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebook.Film'),
        ),
    ]
