# Generated by Django 2.1.5 on 2022-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0003_auto_20220617_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterModelOptions(
            name='herec',
            options={'verbose_name': 'Herec', 'verbose_name_plural': 'Herci'},
        ),
        migrations.AlterModelOptions(
            name='rezie',
            options={'verbose_name': 'Režisér', 'verbose_name_plural': 'Režiséři'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'verbose_name': 'Žánr', 'verbose_name_plural': 'Žánry'},
        ),
        migrations.RemoveField(
            model_name='zanr',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezie',
            name='nazev_rezie',
            field=models.CharField(max_length=80),
        ),
    ]
