# Generated by Django 2.1.5 on 2022-06-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0004_auto_20220617_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezie',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviebook.Zanr'),
        ),
    ]
