# Generated by Django 2.1.5 on 2022-06-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0005_auto_20220617_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rezie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviebook.Rezie'),
        ),
    ]
