# Generated by Django 2.1.5 on 2022-06-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0006_film_rezie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herec',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='herec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviebook.Herec'),
        ),
    ]
